#### not existing contact
GET http://localhost:3000/api/v2/contacts/+123412
#### existing contact
GET http://localhost:3000/api/v2/contacts/+359777223344
### create / update contact
PUT http://localhost:3000/api/v2/contacts/+359777223345 HTTP/1.1
Content-Type: application/json

{
  "firstname": "Johnr",
  "lastname": "Douglas",
  "title": "Mr.",
  "company": "Dev Inc.",
  "jobtitle": "Developer",
  "primarycontactnumber": "+359777223344",
  "othercontactnumbers": [],
  "primaryemailaddress": "john.douglas@xyz.com",
  "emailaddresses": ["j.douglas@xyz.com"],
  "groups": ["Dev"]
}
### remove contact
DELETE http://localhost:3000/api/v2/contacts/+359777223344 HTTP/1.1
### get all contacts in batch
GET http://localhost:3000/api/v2/contacts?page=50 HTTP/1.1
### query contacts in batch
GET http://localhost:3000/api/v2/contacts?groups=Dev HTTP/1.1
###
GET http://localhost:3000/redirect HTTP/1.1


### get image
GET http://localhost:3000/api/v2/contacts/+12345/image HTTP/1.1
### send image
PUT http://localhost:3000/api/v2/contacts/+12345/image HTTP/1.1

< ./IMG_20161223_125428585.jpg
### delete image
DELETE http://localhost:3000/api/v2/contacts/+12345/image HTTP/1.1