#### not existing contact
GET http://localhost:3000/api/v2/contacts/+123412
#### existing contact
GET http://localhost:3000/api/v2/contacts/+359777223344
### create / update contact
PUT http://localhost:3000/api/v2/contacts/+359777223346 HTTP/1.1
Content-Type: application/json

{
  "firstname": "Johnr",
  "lastname": "Douglas",
  "title": "Mr.",
  "company": "Dev Inc.",
  "jobtitle": "Developer",
  "primarycontactnumber": "+359777223344",
  "othercontactnumbers": [],
  "primaryemailaddress": "john.douglas@xyz.com",
  "emailaddresses": ["j.douglas@xyz.com"],
  "groups": ["Dev"]
}
### remove contact
DELETE http://localhost:3000/api/v2/contacts/+359777223344 HTTP/1.1
### get all contacts in batch
GET http://localhost:3000/api/v2/contacts HTTP/1.1